drop table LOC_SITE;

CREATE TABLE "TLOADER"."LOC_SITE" 
   (	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE, 
	"SITE_ID" VARCHAR2(250 BYTE) DEFAULT null NOT NULL ENABLE, 
	"GSV_SITE_ID" NUMBER(5,0) DEFAULT null, 
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT null NOT NULL ENABLE,
	"PARISH" VARCHAR2(250 BYTE) DEFAULT ' ' NOT NULL ENABLE, 
	"PROSPECT" VARCHAR2(250 BYTE) DEFAULT 'UNK' NOT NULL ENABLE, 
	"AMG_ZONE" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"EASTING" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"NORTHING" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LATITUDE" NUMBER DEFAULT 0, 
	"LONGITUDE" NUMBER DEFAULT 0, 
	"LOCN_ACC" NUMBER DEFAULT 0, 
	"LOCN_DATUM_CD" VARCHAR2(5 BYTE) DEFAULT '0' NOT NULL ENABLE, 
	"ELEVATION_GL" NUMBER DEFAULT null, 
	"ELEV_ACC" NUMBER DEFAULT null, 
	"ELEV_DATUM_CD" VARCHAR2(5 BYTE) DEFAULT 'UNK' NOT NULL ENABLE, 
	"COORD_SYSTEM" VARCHAR2(20 BYTE), 
	"VERTICAL_DATUM" VARCHAR2(25 BYTE), 
	"NUM_DATA_RECORDS" NUMBER(5,0) NOT NULL ENABLE, 
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ISSUE_COLUMN_INDEX" NUMBER(5,0) null,
    "UWI" VARCHAR2(250 BYTE) DEFAULT NULL,
    "LOCN_NAME" VARCHAR2(250 BYTE) DEFAULT NULL,
    "LOCN_DESC" VARCHAR2(250 BYTE) DEFAULT NULL,
    "STATE" VARCHAR2(25 BYTE) DEFAULT NULL,
    "BORE_DIAMETER" NUMBER DEFAULT 0,
    "TD" NUMBER DEFAULT 0,
    "TVD" NUMBER DEFAULT 0,
    "KB" NUMBER DEFAULT 0,
    "DEPTH_DATUM" VARCHAR2(5 BYTE) DEFAULT NULL,
	 CONSTRAINT "LOADERID_SITEID_UNIQUE" UNIQUE ("LOADER_ID", "SITE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;



DROP TABLE DH_BOREHOLE;

CREATE TABLE "TLOADER"."DH_BOREHOLE" 
   (	
    "LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE,
    "HOLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE, 
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT null NOT NULL ENABLE,
	"BH_AUTHORITY_CD" VARCHAR2(1 BYTE) DEFAULT 'U' NOT NULL ENABLE, 
	"BH_REGULATION_CD" VARCHAR2(5 BYTE) DEFAULT 'UNK' NOT NULL ENABLE, 
	"DILLING_DETAILS_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE, 
	"DRILLING_START_DT" DATE DEFAULT '01-JAN-1770' NOT NULL ENABLE, 
	"DRILLING_COMPLETION_DT" DATE DEFAULT '01-JAN-1770' NOT NULL ENABLE, 
	"DEPTH" NUMBER DEFAULT NULL, 
	"ELEVATION_KB" NUMBER DEFAULT NULL, 
    "AZIMUTH_MAG" NUMBER DEFAULT NULL,
	"BH_CONFIDENTIAL_FLG" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"DEPTH_UOM" VARCHAR2(10 BYTE) DEFAULT 'MTR' NOT NULL ENABLE, 
	"AZIMUTH" VARCHAR2(20 BYTE), 
	"LOCAL_NAME" VARCHAR2(225 BYTE), 
	"AZIMUTH_UOM" VARCHAR2(20 BYTE), 
	"DIP" VARCHAR2(20 BYTE), 
	"DIP_UOM" VARCHAR2(20 BYTE), 
	  CONSTRAINT "LOADERID_HOLEID_UNIQUE" UNIQUE ("LOADER_ID", "HOLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
 

   --COMMENT ON COLUMN "TLOADER"."DH_BOREHOLE"."SITE_ID" IS 'ID from LOC_SITE RECORD';
 
   COMMENT ON COLUMN "TLOADER"."DH_BOREHOLE"."DILLING_DETAILS_ID" IS 'Identifier from Drilling Details table';
 
   COMMENT ON COLUMN "TLOADER"."DH_BOREHOLE"."DEPTH" IS 'Total depth in ';
 
   COMMENT ON COLUMN "TLOADER"."DH_BOREHOLE"."LOCAL_NAME" IS 'Bore local name Company Hole ID';
   
   DROP TABLE "TLOADER"."TEMPLATE_CONTEXT_PROPERTIES";
   
   CREATE TABLE "TLOADER"."TEMPLATE_CONTEXT_PROPERTIES" 
   (	
    "ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE,
    "TEMPLATE_NAME" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"PROPERTY_NAME" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"PROPERTY_VALUE" VARCHAR2(1000 BYTE) DEFAULT NULL NOT NULL ENABLE, 
      CONSTRAINT "ID_PK" PRIMARY KEY ("ID"),
	  CONSTRAINT "TEMPNAME_PROPNAME_UNIQUE" UNIQUE ("TEMPLATE_NAME", "PROPERTY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
  
  DROP TABLE "TLOADER"."FILE_ERROR_LOG";

CREATE TABLE "TLOADER"."FILE_ERROR_LOG" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"BATCH_ID" NUMBER(25,0) NOT NULL ENABLE, 
    "SEVERITY" VARCHAR2(10 BYTE) DEFAULT 'ERROR' NOT NULL ENABLE,
	"ERROR_MSG" VARCHAR2(4000 BYTE), 
    "CREATED_TIME" TIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "FILE_ERROR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
  
DROP TABLE "TLOADER"."DH_DOWNHOLE";

CREATE TABLE "TLOADER"."DH_DOWNHOLE" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE,
    "HOLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT null NOT NULL ENABLE,
    "SURVEYED_DEPTH" NUMBER DEFAULT NULL NOT NULL ENABLE,
	"AZIMUTH_MAG" NUMBER DEFAULT NULL,
    "DIP" NUMBER DEFAULT NULL NOT NULL ENABLE,
    "AZIMUTH_TRUE" NUMBER DEFAULT NULL,
	 CONSTRAINT "DOWN_HOLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
  
DROP TABLE "TLOADER"."DH_LITHOLOGY";

CREATE TABLE "TLOADER"."DH_LITHOLOGY" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE,
    "HOLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT null NOT NULL ENABLE,
    "DEPTH_FROM" NUMBER DEFAULT NULL NOT NULL ENABLE,
	 CONSTRAINT "LITHOLOGY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
  
DROP TABLE "TLOADER"."DH_GEOCHEMISTRY";

CREATE TABLE "TLOADER"."DH_GEOCHEMISTRY" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE,
    "HOLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "SAMPLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT null NOT NULL ENABLE,
    "SAMPLE_FROM" NUMBER DEFAULT NULL NOT NULL ENABLE,
    "SAMPLE_TO" NUMBER DEFAULT NULL NOT NULL ENABLE,
    "DRILL_CODE" VARCHAR2(10 BYTE) DEFAULT NULL,
	 CONSTRAINT "GEOCHEMISTRY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;  
  
  DROP TABLE "TLOADER"."DH_SURFACE_GEOCHEMISTRY";
  
  CREATE TABLE "TLOADER"."DH_SURFACE_GEOCHEMISTRY" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE,
    "SAMPLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT null NOT NULL ENABLE,
    "EASTING" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"NORTHING" NUMBER DEFAULT 0 NOT NULL ENABLE, 
    "AMG_ZONE" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
    "SAMPLE_TYPE" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ISSUE_COLUMN_INDEX" NUMBER(5,0) null,
	 CONSTRAINT "SURFACE_GEOCHEMISTRY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ; 
  
  DROP TABLE "TLOADER"."DH_OPTIONAL_FIELDS";
  
  CREATE TABLE "TLOADER"."DH_OPTIONAL_FIELDS" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "TEMPLATE_NAME" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "TEMPLATE_HEADER" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
	"ROW_NUMBER"  NUMBER DEFAULT NULL NOT NULL ENABLE, 
    "COLUMN_NUMBER" NUMBER DEFAULT NULL NOT NULL ENABLE,
    "FIELD_VALUE" VARCHAR2(4000 BYTE) DEFAULT NULL,
	 CONSTRAINT "DH_OPTIONAL_FIELDS_PK" PRIMARY KEY ("ID"),
     CONSTRAINT "OP_FLDS_UNIQUE" UNIQUE ("LOADER_ID", "FILE_NAME", "TEMPLATE_NAME", "TEMPLATE_HEADER", "ROW_NUMBER", "COLUMN_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ; 
  
  DROP TABLE "TLOADER"."SESSION_HEADER";
   
  CREATE TABLE "TLOADER"."SESSION_HEADER" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
    "TEMPLATE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
    "FILE_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE,
	"PROCESS_DATE" DATE NOT NULL ENABLE, 
	"TENEMENT" VARCHAR2(250 BYTE), 
	"TENEMENT_HOLDER" VARCHAR2(250 BYTE), 
	"REPORTING_DATE" DATE NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(250 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"EMAIL_SENT" CHAR(1 BYTE) DEFAULT 'N', 
    "APPROVED" NUMBER(1) DEFAULT 0 NOT NULL ENABLE CHECK ( "APPROVED" IN (0,1)),
    "REJECTED" NUMBER(1) DEFAULT 0 NOT NULL ENABLE CHECK( "REJECTED" IN (0,1)),
    "CREATED" TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "SESSION_HEADER_PK" PRIMARY KEY ("ID")
     --, CONSTRAINT "AP_RJ_MT_EXCLUD" CHECK (NOT ("APROVALED" = 1 AND "REJECTED" = 1 ))
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
  
  ALTER TABLE "TLOADER"."SESSION_HEADER"
  ADD CONSTRAINT "APR_REJ_MT_EXCLUD" CHECK (NOT (("APPROVED" = 1) AND ("REJECTED" = 1)));
 

   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."ID" IS 'IDENTIFIER for a single Template group  Load Session ';
   
    COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."TEMPLATE" IS 'Name of the overall template, e.g. MRT ';
    
    COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."FILE_NAME" IS 'Name of the upload file, e.g. MRT_EL123.zip';
 
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."PROCESS_DATE" IS 'DATE process was run ';
 
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."REPORTING_DATE" IS 'MAINLY FOR MRT can be set to process date for internal Templates';
 
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."PROJECT_NAME" IS 'Name of associated Project';
 
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."STATUS" IS 'Status of process';
 
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."EMAIL_SENT" IS 'Has processed emaild owner';
   
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."APPROVED" IS 'Session has been approved';
   
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."REJECTED" IS 'Session has been rejected';
   
   COMMENT ON COLUMN "TLOADER"."SESSION_HEADER"."CREATED" IS 'Session created time';
   
   DROP TABLE "TLOADER"."TEMPLATE_DISPLAY_PROPERTIES";
   
  CREATE TABLE "TLOADER"."TEMPLATE_DISPLAY_PROPERTIES" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
    "TEMPLATE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"DISPLAY_PROPERTIES"  VARCHAR2(4000 BYTE),
    "HEADER_FIELDS" VARCHAR2(4000 BYTE),
    "TEMPLATE_RETRIEVER" VARCHAR2(4000 BYTE),
	 CONSTRAINT "TEMPLATE_DISPLAY_PROP_PK" PRIMARY KEY ("ID"),
      CONSTRAINT "TEMPLATE_UNIQUE" UNIQUE ("TEMPLATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
 

   COMMENT ON COLUMN "TLOADER"."TEMPLATE_DISPLAY_PROPERTIES"."ID" IS 'IDENTIFIER for a single Template group  Load Session ';
   
    COMMENT ON COLUMN "TLOADER"."TEMPLATE_DISPLAY_PROPERTIES"."TEMPLATE" IS 'Name of the overall template, e.g. MRT ';
 
   COMMENT ON COLUMN "TLOADER"."TEMPLATE_DISPLAY_PROPERTIES"."HEADER_FIELDS" IS 'Template header fields ';
   
    COMMENT ON COLUMN "TLOADER"."TEMPLATE_DISPLAY_PROPERTIES"."DISPLAY_PROPERTIES" IS 'Template display fields ';
   
    DROP TABLE "TLOADER"."TEMPLATE_CONFIG";
   
  CREATE TABLE "TLOADER"."TEMPLATE_CONFIG" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"TEMPLATE_NAME" VARCHAR2(250 BYTE), 
	"CLASS_NAMES" VARCHAR2(1000 BYTE), 
    "OWNER_EMAILS" VARCHAR2(1000 BYTE),
    "EMAILS_BUILDER" VARCHAR2(1000 BYTE),
	 CONSTRAINT "TEMPLATE_CONFIG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
 

   COMMENT ON COLUMN "TLOADER"."TEMPLATE_CONFIG"."ID" IS 'IDENTIFIER for a single Template group  Load Session ';
   
    COMMENT ON COLUMN "TLOADER"."TEMPLATE_CONFIG"."TEMPLATE_NAME" IS 'Name of the overall template, e.g. MRT ';
 
   COMMENT ON COLUMN "TLOADER"."TEMPLATE_CONFIG"."CLASS_NAMES" IS 'Template classes, e.g. SL4, DL4 ';
   
   COMMENT ON COLUMN "TLOADER"."TEMPLATE_CONFIG"."OWNER_EMAILS" IS 'Template owners email, e.g. SL4, DL4 ';
   
   COMMENT ON COLUMN "TLOADER"."TEMPLATE_CONFIG"."EMAILS_BUILDER" IS 'Template custom email builder class name';
   
DROP TABLE "TLOADER"."DH_DRILLING_DETAILS";

CREATE TABLE "TLOADER"."DH_DRILLING_DETAILS" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
	"DRILL_TYPE" VARCHAR2(50 BYTE), 
	"DRILL_DESCRIPTION" VARCHAR2(250 BYTE), 
	"DRILL_COMPANY" VARCHAR2(250 BYTE), 
	 CONSTRAINT "DRILLING_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
 

   COMMENT ON COLUMN "TLOADER"."DH_DRILLING_DETAILS"."ID" IS 'Unique Identifier';
   
   COMMENT ON COLUMN "TLOADER"."DH_DRILLING_DETAILS"."FILE_NAME" IS 'File name of data come from';
 
   COMMENT ON COLUMN "TLOADER"."DH_DRILLING_DETAILS"."DRILL_TYPE" IS 'Code Used for Drill Type';
 
   COMMENT ON COLUMN "TLOADER"."DH_DRILLING_DETAILS"."DRILL_DESCRIPTION" IS 'Description of Drill Type';
 
   COMMENT ON COLUMN "TLOADER"."DH_DRILLING_DETAILS"."DRILL_COMPANY" IS 'Drilling company name ';   
   
DROP TABLE "TLOADER"."DH_MANDATORY_HEADERS";

CREATE TABLE "TLOADER"."DH_MANDATORY_HEADERS"
(
    "ID" NUMBER(25,0) NOT NULL ENABLE, 
    "LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE, 
    "TEMPLATE_NAME" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE, 
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT 0 NOT NULL ENABLE, 
    "COLUMN_HEADER" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "FIELD_VALUE" VARCHAR2(50 BYTE) DEFAULT NULL,
    CONSTRAINT "MD_HDRS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
   
 DROP TABLE "TLOADER"."SAMP_METADATA";
   
  CREATE TABLE "TLOADER"."SAMP_METADATA" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE, 
    "SITE_ID" NUMBER(15,0) DEFAULT null NOT NULL ENABLE,
    "SAMPLE_ID" NUMBER(15,0) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT 0 NOT NULL ENABLE,
    "CORE_ID" NUMBER(15,0) DEFAULT NULL,
    "LAB_CODE" VARCHAR2(25 BYTE) DEFAULT NULL,
    "TYPE" VARCHAR2(100 BYTE) DEFAULT NULL,
    "PREP_CODE" VARCHAR2(100 BYTE) DEFAULT NULL,
    "SAMP_DATE" TIMESTAMP DEFAULT NULL,
    "IGSN" VARCHAR2(25 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "SAMP_TOP" NUMBER NOT NULL ENABLE,
    "SAMP_BOTTOM" NUMBER NOT NULL ENABLE,
    "STAND_WATER_LVL" NUMBER NOT NULL ENABLE,
    "PUMPING_DEPTH" NUMBER NOT NULL ENABLE,
    "REFERENCE" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "SAMP_AREA_DESC" VARCHAR2(1000 BYTE) DEFAULT NULL,
	 CONSTRAINT "SAMP_METD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
  
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."ID" IS 'IDENTIFIER for a single sample meta data';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."LOADER_ID" IS 'IDENTIFIER for a single data loading session';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."SITE_ID" IS 'This is the borehole/well ID or if other XXX';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."SAMPLE_ID" IS 'This is the Unique within GSV number';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."CORE_ID" IS 'This is the Core Seq No';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."LAB_CODE" IS 'This is the lab used for the analysis.  E.g. ALS';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."TYPE" IS 'e.g. cutting, core, water, stygofauna, air etc';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."PREP_CODE" IS 'This is how the sample was prepared  prior to analysis.  E.g. grinding';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."SAMP_DATE" IS 'Date of sampling';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."IGSN" IS 'International Geo Sample Number.';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."SAMP_TOP" IS 'This is the "area" within the sample was taken.  It could be the core top or it could be the screen top for a groundwater sample.';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."SAMP_BOTTOM" IS 'This is the "area" within the sample was taken.  It could be the core bottom or it could be the screen bottom for a groundwater sample.';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."STAND_WATER_LVL" IS 'Used for collection of groundwate samples.';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."PUMPING_DEPTH" IS 'Used for collection of groundwate samples.';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."REFERENCE" IS 'This is the addition of a reference to other tabular information.';
COMMENT ON COLUMN "TLOADER"."SAMP_METADATA"."SAMP_AREA_DESC" IS 'Formation/ Aquifer name e.g. Belfast Formation.';

DROP TABLE "TLOADER"."SAMP_ANALYSIS";
   
  CREATE TABLE "TLOADER"."SAMP_ANALYSIS" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE, 
    "SAMPLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT 0 NOT NULL ENABLE,
    "IGSN" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "LAB_SAMP_NO" VARCHAR2(100 BYTE) DEFAULT NULL,
    "ANAL_DATE" TIMESTAMP DEFAULT NULL,
    "PARAM" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "UOM" VARCHAR2(25 BYTE) DEFAULT NULL,
    "RESULT" VARCHAR2(25 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ANAL_METH" VARCHAR2(50 BYTE) DEFAULT NULL,
    "LOR" VARCHAR2(10 BYTE) DEFAULT NULL,
	 CONSTRAINT "SAMP_ANAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
 
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."ID" IS 'IDENTIFIER for a single analyse data';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."LOADER_ID" IS 'IDENTIFIER for a single data loading session';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."SAMPLE_ID" IS 'This is the Unique within GSV number';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."IGSN" IS 'International Geo Sample Number.';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."LAB_SAMP_NO" IS 'An additional and diffierent sample ID.';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."ANAL_DATE" IS 'The date the sample has been analysed.';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."PARAM" IS 'This is what is being analysed.';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."UOM" IS 'Unit Of Measure.';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."RESULT" IS 'The result of anaylse.';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."ANAL_METH" IS 'This is the method of analysis used by lab.';
COMMENT ON COLUMN "TLOADER"."SAMP_ANALYSIS"."LOR" IS 'Limit Of Reporting.';

 DROP TABLE "TLOADER"."OBSERVATIONS";
   
  CREATE TABLE "TLOADER"."OBSERVATIONS" 
   (	"ID" NUMBER(25,0) NOT NULL ENABLE, 
	"LOADER_ID" NUMBER(25,0) DEFAULT NULL NOT NULL ENABLE, 
    "SITE_ID" VARCHAR2(250 BYTE) DEFAULT null NOT NULL ENABLE,
    "SAMPLE_ID" VARCHAR2(250 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "FILE_NAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "ROW_NUMBER"  VARCHAR2(10 BYTE) DEFAULT 0 NOT NULL ENABLE,
    "IGSN" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "OCCUR_TIME" TIMESTAMP DEFAULT NULL,
    "PARAM" VARCHAR2(100 BYTE) DEFAULT NULL NOT NULL ENABLE,
    "DEPTH_FROM" NUMBER DEFAULT NULL,
    "DEPTH_TO" NUMBER DEFAULT NULL,
    "RESULT" VARCHAR2(1000 BYTE) DEFAULT NULL,
    "OBSERVER" VARCHAR2(50 BYTE) DEFAULT NULL,
    "TYPE" VARCHAR2(100 BYTE) DEFAULT NULL,
	 CONSTRAINT "OBS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GEDIS" ;
  
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."ID" IS 'IDENTIFIER for a single sample meta data';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."LOADER_ID" IS 'IDENTIFIER for a single data loading session';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."SITE_ID" IS 'This is the borehole/well ID or if other XXX';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."SAMPLE_ID" IS 'This is the Unique within GSV number';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."IGSN" IS 'International Geo Sample Number.';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."OCCUR_TIME" IS 'This is the date sampled.';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."PARAM" IS 'This is what is being measured or observed.';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."DEPTH_FROM" IS 'This is sample depth from.';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."DEPTH_TO" IS 'This is sample depth to.';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."RESULT" IS 'This is what has been observed.';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."OBSERVER" IS 'This is observe actor.';
  COMMENT ON COLUMN "TLOADER"."OBSERVATIONS"."TYPE" IS 'What general item are you measuring or observing.';